// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('components/close-tab-button.deps.js')
require('components/positive-goal-site-button.deps.js')
import_dom_modules(require('components/call-to-action-button-v2.html'), 'components/call-to-action-button-v2.html')
require('components/call-to-action-button-v2')
